name: EnhancedSurvivalPlugin
version: 1.0.0
author: crazychaoz
main: at.crazychaoz.enhanced_survival.EnhancedSurvivalPlugin
api-version: 1.17
commands:
  quest_blaze:
    description: Spawns a Quest Blaze
    useage: just do it

