name: EnhancedSurvivalPlugin
version: 0.0.1
author: //the author's name
main: at.crazychaoz.enhanced_survival.EnhancedSurvivalPlugin
api-version: 1.16
commands:
  blaze_merchant:
    description: Spawns the Merchant Blaze
    useage: just use it

