name: EnhancedSurvivalPlugin
version: 0.0.1
author: //the author's name
main: at.crazychaoz.enhanced_survival.EnhancedSurvivalPlugin
api-version: 1.16
commands:
  quest_blaze:
    description: Spawns the Quest Blaze
    useage: just use it

